services:

  # server:
  #   image: node:24-slim
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - 3000:3000
  #     - 4000:4000
  #     - 19222:9222
  #   depends_on:
  #     - elastic
  #     - opensearch
  #     - mongo
  #   command: sh -c "
  #       yarn add express@^5 pino@^10 pino-pretty@^13 \
  #                compression@^1 helmet@^8 cors@^2 express-rate-limit@^8 \
  #                swagger-ui-express@^5 swagger-jsdoc@^6 \
  #                graphql@^16 graphql-yoga@^5 @graphql-yoga/plugin-disable-introspection@^2 @escape.tech/graphql-armor@^3 \
  #                @elastic/elasticsearch@^9 @opensearch-project/opensearch@^3 @elastic/elasticsearch-mock@^2\
  #                mongodb@^7 mongodb-memory-server@^10 \
  #                redis@^5 \
  #                amqplib@^0.10 \
  #                mysql2@^3 \
  #                --peer &&
  #       node --permission --allow-fs-read=./ --allow-worker --allow-child-process --watch --inspect=0.0.0.0:9222 ./server.js
  #     "
      
  mongo:
    image: mongo:8-noble
    volumes:
      - ./.data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
      
  elastic:
    image: elasticsearch:9.2.1
    volumes:
      - ./.data/elastic:/usr/share/elasticsearch/data
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
      - 9300:9300

  opensearch:
    image: opensearchproject/opensearch:3
    volumes:
      - ./.data/opensearch:/usr/share/opensearch/data
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Opensearch1!
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - 9500:9200
      - 9600:9600

  redis:
    image: redis:8-alpine
    volumes:
      - ./.data/redis:/data
    ports:
      - 6379:6379

  mysql:
    image: mysql:9
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306

  # rabbitmq:
  #   image: rabbitmq:4-alpine⁠
  #   environment:
  #     RABBITMQ_DEFAULT_USER: root
  #     RABBITMQ_DEFAULT_PASS: root
  #   volumes:
  #     - ./.data/rabbitmq:/var/lib/rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672